import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "QFULLTICKET",
  description: "Generated by create next app",
};

/* Components */
import Link from "next/link";
import Navbar from "./components/Navbar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-[#222] py-2">
          <div className="flex justify-between text-center items-center m-8">
            <Link href={"/"} className="text-center">
              <h1 className="text-4xl font-bold text-lime-400">QFull Ticket</h1>
            </Link>
            <Link href={"/login"}>
              <h3 className="p-2 font-bold text-lime-400 hover:text-[#f5f5f5] hover:bg-lime-400 transition-all duration-300 ease-in-out border rounded-md border-lime-400">
                Login / Register
              </h3>
            </Link>
          </div>
          <div>
            <Navbar />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
